### ISSUE TITLE
Why did you follow me?

### ISSUE THREAD

**Issue by ghost** [jlmendo11/textLinesSegmDL#1]
@jlmendo11 
Why did you follow me?
what was interesting?

**Comment by jlmendo11** [comment]
I guess I misclicked, sorry. I was just watching that you starred my dissertation Project

De: deepseek<mailto:notifications@github.com>
Enviado: viernes, 18 de septiembre de 2020 12:46
Para: jlmendo11/textLinesSegmDL<mailto:textLinesSegmDL@noreply.github.com>
CC: jlmendo11<mailto:jose_luis_co@hotmail.es>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [jlmendo11/textLinesSegmDL] Why did you follow me? (#1)


Reopened #1<https://github.com/jlmendo11/textLinesSegmDL/issues/1>.

**Comment by ghost** [comment]
@jlmendo11 it's fine
which project? send me the link

**Comment by jlmendo11** [comment]
This one: https://github.com/jlmendo11/textLinesSegmDL

If you need something let me know

________________________________
De: deepseek <notifications@github.com>
Enviado: Friday, September 18, 2020 12:50:12 PM
Para: jlmendo11/textLinesSegmDL <textLinesSegmDL@noreply.github.com>
Cc: jlmendo11 <jose_luis_co@hotmail.es>; Mention <mention@noreply.github.com>
Asunto: Re: [jlmendo11/textLinesSegmDL] Why did you follow me? (#1)


@jlmendo11<https://github.com/jlmendo11> it's fine
which project? send me the link

**Comment by ghost** [comment]
are you interested in document layout understanding?

**Comment by jlmendo11** [comment]
It was my bachelor’s dissertation… I’m not really interested anymore

Now my tutor is using the program to build some kind of OCR for old texts

De: deepseek<mailto:notifications@github.com>
Enviado: viernes, 18 de septiembre de 2020 12:51
Para: jlmendo11/textLinesSegmDL<mailto:textLinesSegmDL@noreply.github.com>
CC: jlmendo11<mailto:jose_luis_co@hotmail.es>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [jlmendo11/textLinesSegmDL] Why did you follow me? (#1)


are you interested in document layout understanding?

**Comment by ghost** [comment]
do you have a linkedin page?

**Comment by jlmendo11** [comment]
Yes! Connect with me: https://www.linkedin.com/in/jos%C3%A9-luis-mendoza-s%C3%A1nchez-325207195/

De: deepseek<mailto:notifications@github.com>
Enviado: viernes, 18 de septiembre de 2020 12:54
Para: jlmendo11/textLinesSegmDL<mailto:textLinesSegmDL@noreply.github.com>
CC: jlmendo11<mailto:jose_luis_co@hotmail.es>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [jlmendo11/textLinesSegmDL] Why did you follow me? (#1)


do you have a linkedin page?

**Comment by ghost** [comment]
good luck
